# Generated by Django 4.0.3 on 2022-03-16 19:31

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateResume',
            fields=[
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None, verbose_name='Моб.телефон')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Эл.почта')),
                ('does_not_matter', models.BooleanField(verbose_name='не имеет значения')),
                ('registration', models.CharField(blank=True, choices=[('ashgabat', 'Ашхабад'), ('ahal', 'Ахалский велаят'), ('mary', 'Марыйский велаят'), ('lebap', 'Лебпский велаят'), ('dashoguz', 'Дашогузский велаят'), ('balkan', 'Балканский велаят'), (None, 'не выбрано')], default=None, max_length=50, null=True, verbose_name='Прописка')),
                ('sex', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default=None, max_length=50, null=True, verbose_name='Пол')),
                ('post', models.CharField(max_length=200, verbose_name='Должность')),
                ('Field_of_activity', models.CharField(blank=True, choices=[('service', 'обслуживание'), ('sales, purchases', 'продажи, закупки'), ('education', 'образование'), ('trade', 'торговля'), ('logistics', 'логистика'), ('catering', 'общественное питание'), ('hotel business', 'гостиничный бизнес'), ('beauty and health', 'красота и здоровье'), ('marketing, advertising, PR', 'маркетинг, реклама, PR'), ('finance, accounting, banks', 'финансы, бухгалтерия, банки'), ('medicine', 'медицина'), ('manufacturing', 'производство'), ('law', 'юриспруденция'), ('transport', 'транспорт'), ('other', 'другое'), (None, 'не выбрано')], default=None, max_length=50, null=True, verbose_name='Сфера деятельности')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('busyness', models.CharField(choices=[('full', 'полная занятость'), ('project_work', 'проектная работа'), ('part_time', 'частичная занятость'), ('internship', 'стажировка')], default='full', max_length=50, verbose_name='Занятость')),
                ('work_experience', models.CharField(blank=True, choices=[('yes', 'Есть опыт работы'), ('no', 'Нет опыта работы')], default='yes', max_length=50, null=True, verbose_name='Опыт работы ')),
                ('past_post', models.CharField(max_length=200, verbose_name='Какую должность вы занимали?')),
                ('firm_name', models.CharField(max_length=200, verbose_name='Как называлась организация?')),
                ('responsibilities', models.TextField(blank=True, max_length=200, null=True, verbose_name='Обязательства')),
                ('steel_work', models.BooleanField(verbose_name='Работаю по настоящее время')),
                ('education', models.CharField(blank=True, choices=[('secondary', 'среднее'), ('secondary_special', 'среднее-специальное'), ('incomplete_higher', 'неоконченное высшее'), ('higher', 'высшее'), ('master', 'магистр'), ('candidate_of_sciences', 'кандидат наук'), ('doctor_of_science', 'доктор наук'), (None, 'не выбрано')], default=None, max_length=50, null=True, verbose_name='Образование')),
                ('universitet', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('knowledge_of_programs', models.CharField(blank=True, choices=[('1c', '1C'), ('ms_office', 'MS Office')], default='ms_office', max_length=50, null=True, verbose_name='Знание программ ')),
                ('language', models.CharField(choices=[('eng', 'английский'), ('rus', 'русский'), ('tur', 'туркменский')], default='eng', max_length=50, verbose_name='Владение языками')),
                ('level', models.IntegerField(blank=True, choices=[(0, 'не владею'), (1, 'элементарный'), (3, 'ниже среднего')], default=0, null=True)),
                ('about_yourself', models.TextField(blank=True, max_length=200, null=True, verbose_name='О себе')),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateVacancy',
            fields=[
                ('post', models.CharField(max_length=200, verbose_name='Должность')),
                ('Field_of_activity', models.CharField(blank=True, choices=[('service', 'обслуживание'), ('sales, purchases', 'продажи, закупки'), ('education', 'образование'), ('trade', 'торговля'), ('logistics', 'логистика'), ('catering', 'общественное питание'), ('hotel business', 'гостиничный бизнес'), ('beauty and health', 'красота и здоровье'), ('marketing, advertising, PR', 'маркетинг, реклама, PR'), ('finance, accounting, banks', 'финансы, бухгалтерия, банки'), ('medicine', 'медицина'), ('manufacturing', 'производство'), ('law', 'юриспруденция'), ('transport', 'транспорт'), ('other', 'другое'), (None, 'не выбрано')], default=None, max_length=50, null=True, verbose_name='Сфера деятельности')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('does_not_matter', models.BooleanField(verbose_name='не имеет значения')),
                ('registration', models.CharField(blank=True, choices=[('ashgabat', 'Ашхабад'), ('ahal', 'Ахалский велаят'), ('mary', 'Марыйский велаят'), ('lebap', 'Лебпский велаят'), ('dashoguz', 'Дашогузский велаят'), ('balkan', 'Балканский велаят'), (None, 'не выбрано')], default=None, max_length=50, null=True, verbose_name='Прописка')),
                ('employee_requirements', models.IntegerField(blank=True, choices=[(None, 'не имеет значение'), (0, 'нет опыта'), (3, 'от 1-3 лет'), (5, 'от 3-5 лет'), (6, 'более 6 лет')], default=None, null=True, verbose_name='Требования к сотруднику')),
                ('age_min', models.IntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_max', models.IntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('sex', models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский'), (None, 'не имеет значения')], default=None, max_length=50, null=True, verbose_name='Пол')),
                ('education', models.CharField(blank=True, choices=[('secondary', 'среднее'), ('secondary_special', 'среднее-специальное'), ('incomplete_higher', 'неоконченное высшее'), ('higher', 'высшее'), ('master', 'магистр'), ('candidate_of_sciences', 'кандидат наук'), ('doctor_of_science', 'доктор наук'), (None, 'не выбрано')], default=None, max_length=50, null=True, verbose_name='Образование')),
                ('language', models.CharField(choices=[('eng', 'английский'), ('rus', 'русский'), ('tur', 'туркменский')], default='eng', max_length=50, verbose_name='Владение языками')),
                ('level', models.IntegerField(blank=True, choices=[(0, 'не владею'), (1, 'элементарный'), (3, 'ниже среднего')], default=0, null=True)),
                ('responsibilities', models.TextField(blank=True, max_length=200, null=True, verbose_name='Обязанности')),
                ('working_conditions', models.TextField(blank=True, max_length=200, null=True, verbose_name='Условия работы')),
                ('busyness', models.CharField(choices=[('full', 'полная занятость'), ('project_work', 'проектная работа'), ('part_time', 'частичная занятость'), ('internship', 'стажировка')], default='full', max_length=50, verbose_name='Занятость')),
                ('schedule', models.CharField(choices=[('full', 'полная рабочий день'), ('shift_schedule', 'сменный график'), ('flexible_schedule', 'гибкий график'), ('remote_work', 'удаленная работа')], default='remote_work', max_length=50, verbose_name='Занятость')),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
