# Generated by Django 4.0.3 on 2022-03-18 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createresume',
            name='language',
        ),
        migrations.RemoveField(
            model_name='createresume',
            name='level',
        ),
        migrations.RemoveField(
            model_name='createvacancy',
            name='language',
        ),
        migrations.RemoveField(
            model_name='createvacancy',
            name='level',
        ),
        migrations.AlterField(
            model_name='createresume',
            name='busyness',
            field=models.CharField(blank=True, choices=[('full', 'полная занятость'), ('project_work', 'проектная работа'), ('part_time', 'частичная занятость'), ('internship', 'стажировка')], default='full', max_length=50, null=True, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='firm_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Как называлась организация?'),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='past_post',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Какую должность вы занимали?'),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='createresume',
            name='universitet',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='createvacancy',
            name='busyness',
            field=models.CharField(blank=True, choices=[('full', 'полная занятость'), ('project_work', 'проектная работа'), ('part_time', 'частичная занятость'), ('internship', 'стажировка')], default='full', max_length=50, null=True, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='createvacancy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='createvacancy',
            name='schedule',
            field=models.CharField(blank=True, choices=[('full', 'полная рабочий день'), ('shift_schedule', 'сменный график'), ('flexible_schedule', 'гибкий график'), ('remote_work', 'удаленная работа')], default='remote_work', max_length=50, null=True, verbose_name='График работы'),
        ),
    ]
