# Generated by Django 4.0.3 on 2022-03-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_createresume_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('eng', 'английский'), ('rus', 'русский'), ('tur', 'туркменский')], default='eng', max_length=50, verbose_name='Владение языками')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, choices=[(0, 'не владею'), (1, 'элементарный'), (3, 'ниже среднего')], default=0, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.createresume')),
            ],
        ),
        migrations.AddField(
            model_name='createresume',
            name='lang1',
            field=models.ManyToManyField(blank=True, to='board.language'),
        ),
    ]
